# Generated by Django 5.1.3 on 2024-12-08 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(blank=True, upload_to='menu_images')),
                ('category', models.CharField(choices=[('A', 'Appetizer'), ('E', 'Entree'), ('M', 'Main'), ('S', 'Side'), ('D', 'Dessert'), ('B', 'Beverage'), ('O', 'Other')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('C', 'Completed'), ('D', 'Delivered'), ('N', 'Not Paid')], max_length=1)),
                ('date', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('menu', models.ManyToManyField(to='main_app.menu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('categories', models.CharField(choices=[('A', 'Appetizer'), ('E', 'Entree'), ('M', 'Main'), ('S', 'Side'), ('D', 'Dessert'), ('B', 'Beverage'), ('O', 'Other')], max_length=1)),
                ('image', models.ImageField(blank=True, upload_to='restaurant_images')),
                ('menu', models.ManyToManyField(to='main_app.menu')),
                ('orders_history', models.ManyToManyField(blank=True, to='main_app.order')),
            ],
        ),
    ]
