# Generated by Django 5.1.3 on 2024-12-09 08:01

from django.db import migrations, models

def populate_categories(apps, schema_editor):
    Category = apps.get_model('main_app', 'Category')
    categories = [
        ('A', 'Appetizer'),
        ('B', 'Beverage'),
        ('D', 'Dessert'),
        ('E', 'Entree'),
        ('M', 'Main'),
        ('S', 'Side'),
        ('O', 'Other'),
    ]
    for code, name in categories:
        Category.objects.get_or_create(code=code, name=name)

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='categories',
            field=models.ManyToManyField(to='main_app.category'),
        ),
        migrations.RunPython(populate_categories),
    ]
