# Generated by Django 5.1.3 on 2024-12-08 11:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_menu_image_restaurant_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.CharField(choices=[('A', 'Appetizer'), ('E', 'Entree'), ('M', 'Main'), ('S', 'Side'), ('D', 'Dessert'), ('B', 'Beverage'), ('O', 'Other')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('A', 'Appetizer'), ('E', 'Entree'), ('M', 'Main'), ('S', 'Side'), ('D', 'Dessert'), ('B', 'Beverage'), ('O', 'Other')], default='A', max_length=1), size=None),
        ),
    ]
