# Generated by Django 5.1.3 on 2024-12-09 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_profile_email'),
        ('main_app', '0007_alter_menu_description_alter_menu_price'),
    ]

    operations = [
    ]
