# Generated by Django 5.1.3 on 2024-12-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('RestaurantOwner', 'Restaurant Owner'), ('Customer', 'Customer')], default='Customer', max_length=20),
        ),
    ]
