# Generated by Django 5.1.3 on 2024-12-11 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_menuorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuorder',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.order'),
            preserve_default=False,
        ),
    ]
