# Generated by Django 5.1.4 on 2024-12-11 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_profile_role'),
        ('main_app', '0011_menuorder_order'),
    ]

    operations = [
    ]
