# Generated by Django 5.1.4 on 2024-12-11 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_merge_0010_profile_role_0011_menuorder_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.restaurant'),
        ),
    ]
